# Open new windows in current path
bind N new-window -c "#{pane_current_path}"

# Open new panes in current path
bind H split-window -h -c "#{pane_current_path}"
bind V split-window -v -c "#{pane_current_path}"

# Rename current window & session
bind W command-prompt -I "#W" { rename-window "%%" }
bind S command-prompt -I "#S" { rename-session "%%" }

# Close current window
bind Q confirm-before -p "kill-window #W? (y/n)" kill-window

set -g set-clipboard on
set -g status-position top
set -g renumber-windows on
set -g terminal-overrides ",*:RGB"

# Catppuccin
set -g @catppuccin_flavor "mocha"

# Window styling
set -g window-status-separator "|"
set -g status-left-length 0
set -g status-left " #{?client_prefix,#[fg=#{@thm_red} bold],#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold],#[fg=#{@thm_green} bold]}}TMUX #[fg=#{@thm_fg} bold]| "

set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_current_number_color "#{@thm_mauve}"
set -g @catppuccin_window_current_number "#[bold]#I: #W  "
set -g @catppuccin_window_current_text ""

set -g @catppuccin_window_current_left_separator " "
set -g @catppuccin_window_current_middle_separator ""
set -g @catppuccin_window_current_right_separator ""

set -g @catppuccin_window_number_color "#{@thm_surface_0}"
set -g @catppuccin_window_number "#[fg=#{@thm_fg} bold]#I: #W  "
set -g @catppuccin_window_text ""

set -g @catppuccin_window_status_style "custom"

set -g @catppuccin_window_left_separator " "
set -g @catppuccin_window_middle_separator ""
set -g @catppuccin_window_right_separator ""

set -g status-right "#[fg=#{@thm_peach} bold] [#S] #[fg=#{@thm_fg} bold]| "
set -ga status-right "#[fg=#{@thm_blue} bold]󰃰 %a %d/%m/%Y ~ %H:%M "