# Disable blur for floating XWayland window
windowrulev2 = noblur,class:^(.*)$

# Development
windowrulev2 = workspace 1 silent, class:^(code)$
windowrulev2 = workspace 1 silent, class:^(ghostty)$

# Web / research
windowrulev2 = workspace 2 silent, class:^(firefox)$

# Communication / media
windowrulev2 = workspace 3 silent, class:^(discord)$
windowrulev2 = workspace 3 silent, class:^(Spotify)$

# Gaming
windowrulev2 = workspace 4 silent, class:^(steam)$