# Disable blur for floating XWayland window
windowrulev2 = noblur,class:^(.*)$

windowrulev2 = workspace 1,class:^(code)$
windowrulev2 = workspace 2,class:^(discord)$
windowrulev2 = workspace 2,class:^(spotify)$
windowrulev2 = workspace 6,class:^(ghostty)$
windowrulev2 = workspace 7,class:^(firefox)$