# Disable blur for floating XWayland window
windowrulev2 = noblur,class:^(.*)$

windowrulev2 = workspace 1,class:^(code)$
windowrulev2 = workspace 2,class:^(discord)$
windowrulev2 = workspace 2,class:^(Spotify)$
windowrulev2 = workspace 6,class:^(firefox)$